FROM registry.access.redhat.com/ubi8/nginx-120
EXPOSE 8443
COPY ./nginx-conf/nginx-tls.conf "${NGINX_CONF_PATH}"
COPY ./dist/mock-tvm /opt/app-root/src
COPY ./tls-crt/server.crt /etc/pki/nginx/server.crt
COPY ./tls-crt/server.key /etc/pki/nginx/private/server.key
CMD nginx -g "daemon off;"
