FROM registry.access.redhat.com/ubi8/openjdk-11:latest
ENV APP_HOME=/home/jboss APP_NAME=demo-app
EXPOSE 8080
WORKDIR ${APP_HOME}
COPY ./ ./
USER root
RUN mvn clean package
RUN chown jboss:root ${APP_HOME} && \
    chmod -R 755 ${APP_HOME}
USER jboss
CMD [ "java","-jar","target/demo-app-0.0.1-SNAPSHOT.jar" ]
